import { Inter } from 'next/font/google'
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Header from './Header';
import CssBaseline  from '../components/mui-use-client/CssBaseline';
import Container from '../components/mui-use-client/Container';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CssBaseline />
        <Header />
          <Container maxWidth='xl' sx={{ py: 2 }}>
            {children}
          </Container>
      </body>
    </html>
  )
}
